Aca va mi presentacion!
circulo-aprendizaje/organizacion pull request #15
Opened 2017-11-22 16:36 UTC by poloagustin

2017-11-22 20:19 UTC, hrajchert requested changes

2017-11-22 20:19 UTC, hrajchert commented on mensajes/agustin_polo.md
> +#Daniel Gómez
Dani polo, sos vos?

2017-11-22 20:19 UTC, hrajchert commented on README.md
> +| [Agustin Polo](https://github.com/circulo-aprendizaje/organizacion/blob/master/mensajes/agustin_polo.md) | React, FP, Typescript | 3-4hs |
Te pido por favor de mantener orden alfabetico :)?

2017-11-22 20:21 UTC, poloagustin commented
@hrajchert ahi cambie otras cosas :)

2017-11-22 20:22 UTC, poloagustin commented on mensajes/agustin_polo.md
> +#Daniel Gómez
done!

2017-11-23 14:07 UTC, hrajchert approved these changes

2017-11-23 14:07 UTC, merged